### ISSUE TITLE
API for adding to search history and view history

### ISSUE THREAD

**Issue by Zeiser** [IT2810/it2810-webutvikling-h17-prosjekt-4-group-12#19]

**Comment by Zeiser** [comment]
@michaehg createdAtdate inkluderer ikke klokkeslett

**Comment by michaehg** [comment]
https://github.com/IT2810/it2810-webutvikling-h17-prosjekt-4-group-12/commit/718e1b5c944585dae9dcef1c8b7ad25c8de4bcf7
Løser dette.
