### ISSUE TITLE
Movie List View

### ISSUE THREAD

**Issue by Zeiser** [IT2810/it2810-webutvikling-h17-prosjekt-4-group-12#8]

**Comment by tobinus** [comment]
I believe we fullfill the criteria with the current implementation of the movie list view. It has support for: 
* searching by title
* set a range of release dates
* choose between three fields to order by
* choose between ascending or descending
* filtering by genres and keywords like before

It would still be nice with automatic loading and state in URL, but I think they should be separate issues.
